[package]
authors = ["David Peter <mail@david-peter.de>"]
categories = ["command-line-utilities"]
description="A cat(1) clone with wings."
homepage = "https://github.com/sharkdp/bat"
license = "MIT/Apache-2.0"
name = "bat"
readme = "README.md"
repository = "https://github.com/sharkdp/bat"
version = "0.9.0"
exclude = [
    "assets/syntaxes/*",
    "assets/themes/*",
]

[workspace]
members = [".", "batwing"]

[dependencies]
batwing = { version = "0.9.0", path = "batwing", features = ["cli"] }
lazy_static = "1.2"

[dependencies.git2]
version = "0.8"
default-features = false
features = []

[dev-dependencies]
tempdir = "0.3"
assert_cmd = "0.10.2"
escargot = "0.4.0"